import type { Translations } from './en'

const ar: Translations = {
  nav: { marketplace: 'السوق', trade: 'التداول', live: 'مباشر', guild: 'النقابة', vault: 'الخزنة', studio: 'الاستوديو' },
  header: { notifications: 'الإشعارات', markAllRead: 'تحديد الكل كمقروء', allCaughtUp: 'لا إشعارات جديدة', viewAllActivity: 'عرض كل النشاط', clearAll: 'مسح الكل', all: 'الكل', unread: 'غير مقروء', signOut: 'تسجيل الخروج', connectWallet: 'ربط المحفظة' },
  lang: { label: 'اللغة', search: 'البحث عن لغة…' },
  common: { viewDetailReviews: 'عرض التفاصيل والمراجعات', buy: 'شراء', sell: 'بيع', collect: 'جمع', noReviewsYet: 'لا مراجعات بعد', loading: 'جارٍ التحميل…', error: 'حدث خطأ ما', search: 'بحث…', noResults: 'لا نتائج', live: 'مباشر', back: 'رجوع', cancel: 'إلغاء', confirm: 'تأكيد' },
  marketplace: { title: 'السوق المباشر', subtitle: 'تداول أعمالاً فنية فريدة على منحنى الربط.', totalVolume: 'إجمالي الحجم', listings: 'المدرجة', trades24h: 'صفقات 24 ساعة', all: 'الكل', search: 'بحث…', race: 'سباق', marketCap: 'القيمة السوقية', change24h: 'تغير 24 ساعة', change7d: 'تغير 7 أيام', liveActivity: 'النشاط المباشر' },
  trade: { markets: 'الأسواق', search: 'بحث…', change24h: 'تغير 24 ساعة', vol24h: 'حجم 24 ساعة', high24h: 'أعلى 24 ساعة', low24h: 'أدنى 24 ساعة', holders: 'الحاملون', progress: 'التقدم', recentTrades: 'الصفقات الأخيرة', orderBook: 'دفتر الأوامر', time: 'الوقت', side: 'الاتجاه', price: 'السعر', size: 'الكمية', sizeEth: 'الكمية (ETH)', total: 'الإجمالي', wallet: 'المحفظة', priceEth: 'السعر (ETH)', bal: 'الرصيد', max: 'الحد الأقصى', youPay: 'تدفع', youReceive: 'تستلم', estimate: 'تقدير', impact: 'التأثير', minOut: 'الحد الأدنى للاستلام', graduationWarning: 'هذه الصفقة ستنقل العمل إلى DEX', youSell: 'تبيع', slippage: 'الانزلاق', confirming: 'جارٍ التأكيد…', orderExecuted: 'تم تنفيذ الأمر', noResults: 'لا نتائج' },
  guild: { joined: 'منضم', guilds: 'النقابات', discover: 'اكتشاف', myGuilds: 'نقاباتي', statsFormat: '{count} نقابة · {members} عضو', createGuild: '+ إنشاء نقابة', createModalTitle: 'إنشاء نقابة', guildNameLabel: 'اسم النقابة', guildNamePlaceholder: 'مثال: جمعية النكتورن', descriptionLabel: 'الوصف', descriptionPlaceholder: 'ماذا تجمع نقابتك وتحتفل به؟', focusLabel: 'التركيز', createButton: '✦ إنشاء النقابة', activity: 'النشاط', chat: 'الدردشة', members: 'الأعضاء', holdings: 'الحيازات', leave: 'مغادرة', joinGuild: 'الانضمام', reply: 'رد', chatPlaceholder: 'رسالة إلى {name}…', collectiveHoldings: 'الحيازات الجماعية', positions: 'المراكز', noHoldingsData: 'لا بيانات حيازات جماعية', moreMembers: '+{count} أعضاء آخرون', tokens: '{count} رمز', qty: 'الكمية', pctCollective: '% الجماعي' },
  live: { home: 'الرئيسية', live: 'مباشر', artists: 'الفنانون', you: 'أنت', all: 'الكل', following: 'المتابَعون', videos: 'مقاطع الفيديو', painting: 'الرسم', drawing: 'الرسم بالقلم', digital: 'رقمي', sculpture: 'النحت', mixedMedia: 'وسائط مختلطة', trending: 'الأكثر رواجاً', watching: '{count} يشاهدون', saveToPlaylist: 'حفظ في القائمة', share: 'مشاركة', report: 'إبلاغ', moreOptions: 'المزيد من الخيارات', goLive: 'بث مباشر', streamTitleLabel: 'عنوان البث', streamTitlePlaceholder: 'ماذا تصنع اليوم؟', categoryLabel: 'الفئة', starting: 'جارٍ البدء…', startStreaming: '● بدء البث', goLiveButton: 'بث مباشر', noContent: 'لا محتوى في هذه الفئة' },
  studio: { createArtwork: 'إنشاء عمل فني', uploadPrompt: 'رفع العمل · JPG / PNG / WEBP / MP4', uploadHint: 'الحد الأقصى 50 ميغابايت · الحد الأدنى 1200×1200 بكسل', artworkTitleLabel: 'عنوان العمل', artworkTitlePlaceholder: 'مثال: دراسة التفكك III', tickerLabel: 'رمز التوكن', tickerHint: 'مُولَّد تلقائياً · قابل للتعديل', categoryLabel: 'الفئة', descriptionLabel: 'الوصف', descriptionPlaceholder: 'صف عملك الفني…', bondingCurveTypeLabel: 'نوع منحنى الربط', totalSupplyLabel: 'إجمالي العرض', initPriceLabel: 'السعر الابتدائي (ETH)', creatorRoyaltyLabel: 'حقوق المبدع', aiModeration: 'مراجعة الذكاء الاصطناعي…', launchArtwork: '✦ إطلاق العمل', previewLabel: 'معاينة', curveLabel: 'منحنى {type}', initPriceCard: 'السعر الابتدائي', supplyCard: 'العرض', royaltyCard: 'حقوق الملكية', bondingCurveChart: 'منحنى الربط', priceVsSupply: 'السعر مقابل العرض', supply80: '80% عرض', targetPrice: 'السعر المستهدف', at80Supply: 'عند 80% عرض', ethToGrad: 'ETH للتخرج', graduationThreshold: 'عتبة التخرج', estGasCost: 'رسوم الغاز المقدرة', deployDesc: 'نشر على Base · منحنى {type}', launchChecklist: 'قائمة الإطلاق', stepUpload: 'رفع العمل', stepTitle: 'العنوان والوصف', stepTicker: 'تحديد الرمز', stepCategory: 'اختيار الفئة', stepCurve: 'تكوين المنحنى', stepAiCheck: 'فحص الذكاء الاصطناعي', stepWallet: 'ربط المحفظة', stepGas: 'رصيد الغاز كافٍ', stepDeploy: 'النشر', awaitingSubmission: 'في انتظار الإرسال…', aiCheckDescription: 'يتحقق الذكاء الاصطناعي من تعارضات الملكية الفكرية والمحتوى المحظور.', analyzing: 'جارٍ تحليل العمل…', approved: 'موافق عليه — جاهز للإطلاق', approvedDetails: 'لا تعارضات ملكية فكرية · المعايير مستوفاة', rejected: 'مرفوض', rejectedMessage: 'تم اكتشاف تعارض محتمل في الملكية الفكرية.', breadcrumbStudio: 'الاستوديو', breadcrumbNew: 'عمل جديد', connected: 'متصل: {addr}', notConnected: 'غير متصل' },
  vault: { portfolioValue: 'قيمة المحفظة', timeframe7d: '7أ', timeframe30d: '30أ', timeframe90d: '90أ', allocation: 'التخصيص', total: 'الإجمالي', portfolioValueStat: 'قيمة المحفظة', unrealizedPnl: 'ربح/خسارة غير محقق', realizedPnl: 'ربح/خسارة محقق', ethBalance: 'رصيد ETH', myHoldings: 'حيازاتي', txHistory: 'سجل المعاملات', asset: 'الأصل', qty: 'الكمية', avgBuy: 'متوسط الشراء', current: 'الحالي', value: 'القيمة', pnl: 'ر/خ', chgPct: 'تغير %', date: 'التاريخ', side: 'الاتجاه', token: 'التوكن', ethSpent: 'ETH المنفق', buy: 'شراء', sell: 'بيع', realizedPnlClosed: 'ربح/خسارة محقق (مغلق)', tradeLink: 'تداول →', noResults: 'لا نتائج' },
  settings: { title: 'الإعدادات', accountSettings: 'إعدادات الحساب', accountSettingsDesc: 'إدارة ملفك الشخصي والأمان والتفضيلات.', profileSection: 'الملف الشخصي', usernameLabel: 'اسم المستخدم', usernamePlaceholder: 'اسم_المستخدم', bioLabel: 'النبذة', bioPlaceholder: 'عرّف نفسك للعالم…', saving: 'جارٍ الحفظ…', saved: '✓ تم الحفظ', saveChanges: 'حفظ التغييرات', notificationsSection: 'الإشعارات', tradeAlerts: 'تنبيهات التداول', tradeAlertsDesc: 'تلقي إشعار عند تداول أعمالك', newFollowers: 'متابعون جدد', newFollowersDesc: 'عندما يتابع أحد ملفك', priceMilestones: 'معالم السعر', priceMilestonesDesc: 'عندما يصل عمل فني إلى هدف سعري', securitySection: 'الأمان', authMethod: 'طريقة المصادقة', authMethodDesc: 'كيف تسجل الدخول إلى ArtCurve', session: 'الجلسة', sessionDesc: 'أنت مسجل الدخول حالياً', active: 'نشط', dangerZone: 'منطقة الخطر', signOut: 'تسجيل الخروج', signOutDesc: 'تسجيل الخروج من حسابك على هذا الجهاز' },
  wallet: { signInTitle: 'سجّل الدخول لعرض محفظتك', signInDesc: 'تواصل عبر GitHub أو X أو محفظة مشفرة للوصول إلى محفظتك.', title: 'المحفظة', yourWallet: 'محفظتك', walletDesc: 'إدارة هويتك ورصيدك ونشاطك على السلسلة.', verified: 'موثّق', anonymous: 'مجهول', signOut: 'تسجيل الخروج', connectedWallet: 'المحفظة المتصلة', accountAddress: 'عنوان الحساب', smartAccount: 'حساب ذكي · تدار بواسطة المنصة', copy: 'نسخ', copied: 'تم النسخ', explorer: 'المستكشف', ethBalance: 'رصيد ETH', emptyWallet: 'المحفظة فارغة', walletNotConnected: 'المحفظة غير متصلة', portfolio: 'المحفظة الاستثمارية', noPositions: 'لا مراكز', holdingsCount: '{count} حيازة', holdingsCountPlural: '{count} حيازات', network: 'الشبكة', authMethod: 'طريقة المصادقة', portfolioHoldings: 'حيازات المحفظة', totalPnl: 'إجمالي الربح/الخسارة:', linkWalletTitle: 'ربط محفظة خارجية', linkWalletDesc: 'قم بتوصيل MetaMask أو محفظة أخرى للتداول على السلسلة.', noWalletsDetected: 'لم يتم اكتشاف محافظ', noWalletsHint: 'قم بتثبيت MetaMask أو إضافة محفظة أخرى', getMetaMask: 'الحصول على MetaMask', showLess: 'عرض أقل', showMore: 'عرض {count} محافظ إضافية', detected: 'تم الاكتشاف', securitySection: 'الأمان', signInMethod: 'طريقة تسجيل الدخول', walletVerification: 'التحقق من المحفظة', onChainWallet: 'محفظة على السلسلة (SIWE)', verifiedViaSiwe: 'تم التحقق عبر EIP-4361', notVerified: 'غير موثّق', accountRole: 'دور الحساب', artist: 'فنان — يمكنه صك الأعمال', admin: 'مدير', collector: 'جامع', userId: 'معرّف المستخدم' },
  artwork: { backToMarketplace: 'العودة إلى السوق', marketCap: 'القيمة السوقية', change24h: 'تغير 24 ساعة', holders: 'الحاملون', volume24h: 'حجم 24 ساعة', completion: 'الاكتمال', phase: 'المرحلة', graduated: '✦ تخرّج', bondingCurve: 'منحنى الربط', priceVsSupply: 'السعر مقابل العرض', now: 'الآن', buy: 'شراء {ticker}', collectorVoices: 'أصوات الجامعين', poor: 'ضعيف', fair: 'مقبول', good: 'جيد', great: 'جيد جداً', exceptional: 'استثنائي', sharePerspective: 'شارك وجهة نظرك حول هذا العمل…', posting: 'جارٍ النشر…', post: 'نشر', connectToShare: 'اربط محفظتك للمشاركة.', connect: 'ربط', noPerspectives: 'لا وجهات نظر بعد.', artworkNotFound: 'لم يتم العثور على العمل', topHolders: 'أكبر الحاملين' },
  error: { systemError: 'خطأ في النظام', somethingWentWrong: 'حدث خطأ ما', tryAgain: 'حاول مرة أخرى' },
  notFound: { label: 'الصفحة غير موجودة', description: 'هذا المنحنى غير موجود — أو لم يتم نشره بعد.', returnToMarket: 'العودة إلى السوق' },
  auth: { signingIn: 'جارٍ تسجيل الدخول…' },
}

export default ar
