import type { Translations } from './en'

const de: Translations = {
  nav: { marketplace: 'Marktplatz', trade: 'Handel', live: 'Live', guild: 'Gilde', vault: 'Tresor', studio: 'Studio' },
  header: { notifications: 'Benachrichtigungen', markAllRead: 'Alle als gelesen markieren', allCaughtUp: 'Keine neuen Benachrichtigungen', viewAllActivity: 'Alle Aktivitäten anzeigen', clearAll: 'Alle löschen', all: 'Alle', unread: 'Ungelesen', signOut: 'Abmelden', connectWallet: 'Wallet verbinden' },
  lang: { label: 'Sprache', search: 'Sprache suchen…' },
  common: { viewDetailReviews: 'Details & Bewertungen anzeigen', buy: 'Kaufen', sell: 'Verkaufen', collect: 'Sammeln', noReviewsYet: 'Noch keine Bewertungen', loading: 'Lädt…', error: 'Etwas ist schiefgelaufen', search: 'Suchen…', noResults: 'Keine Ergebnisse', live: 'Live', back: 'Zurück', cancel: 'Abbrechen', confirm: 'Bestätigen' },
  marketplace: { title: 'Live-Marktplatz', subtitle: 'Handeln Sie einzigartige Kunstwerke auf der Bonding-Kurve.', totalVolume: 'Gesamtvolumen', listings: 'Aktive Listings', trades24h: '24H-Trades', all: 'Alle', search: 'Suchen…', race: 'Rennen', marketCap: 'Marktkapitalisierung', change24h: '24h-Änderung', change7d: '7d-Änderung', liveActivity: 'Live-Aktivität' },
  trade: { markets: 'Märkte', search: 'Suchen…', change24h: '24H-Änderung', vol24h: '24H-Vol.', high24h: '24H-Hoch', low24h: '24H-Tief', holders: 'Inhaber', progress: 'Fortschritt', recentTrades: 'Letzte Trades', orderBook: 'Orderbuch', time: 'Zeit', side: 'Seite', price: 'Preis', size: 'Menge', sizeEth: 'Menge (ETH)', total: 'Gesamt', wallet: 'Wallet', priceEth: 'Preis (ETH)', bal: 'Guthaben', max: 'MAX', youPay: 'Sie zahlen', youReceive: 'Sie erhalten', estimate: 'Schätzung', impact: 'Auswirkung', minOut: 'Mindesterhalt', graduationWarning: 'Dieser Trade würde das Kunstwerk zum DEX graduieren', youSell: 'Sie verkaufen', slippage: 'Slippage', confirming: 'Bestätigung…', orderExecuted: 'Order ausgeführt', noResults: 'Keine Ergebnisse' },
  guild: { joined: 'Beigetreten', guilds: 'Gilden', discover: 'Entdecken', myGuilds: 'Meine Gilden', statsFormat: '{count} Gilden · {members} Mitglieder', createGuild: '+ Gilde erstellen', createModalTitle: 'Gilde erstellen', guildNameLabel: 'Gildenname', guildNamePlaceholder: 'z.B. Die Nokturne-Gesellschaft', descriptionLabel: 'Beschreibung', descriptionPlaceholder: 'Was sammelt und feiert Ihre Gilde?', focusLabel: 'Fokus', createButton: '✦ Gilde erstellen', activity: 'Aktivität', chat: 'Chat', members: 'Mitglieder', holdings: 'Bestände', leave: 'Verlassen', joinGuild: 'Gilde beitreten', reply: 'Antworten', chatPlaceholder: 'Nachricht an {name}…', collectiveHoldings: 'Kollektive Bestände', positions: 'Positionen', noHoldingsData: 'Keine kollektiven Bestandsdaten', moreMembers: '+{count} weitere Mitglieder', tokens: '{count} Token', qty: 'Menge', pctCollective: '% Kollektiv' },
  live: { home: 'Startseite', live: 'Live', artists: 'Künstler', you: 'Sie', all: 'Alle', following: 'Gefolgt', videos: 'Videos', painting: 'Malerei', drawing: 'Zeichnung', digital: 'Digital', sculpture: 'Skulptur', mixedMedia: 'Mixed Media', trending: 'Trending', watching: '{count} schauen zu', saveToPlaylist: 'In Wiedergabeliste speichern', share: 'Teilen', report: 'Melden', moreOptions: 'Weitere Optionen', goLive: 'Live gehen', streamTitleLabel: 'Stream-Titel', streamTitlePlaceholder: 'Was erstellen Sie heute?', categoryLabel: 'Kategorie', starting: 'Startet…', startStreaming: '● Streaming starten', goLiveButton: 'Live gehen', noContent: 'Kein Inhalt in dieser Kategorie' },
  studio: { createArtwork: 'Kunstwerk erstellen', uploadPrompt: 'Kunstwerk ablegen · JPG / PNG / WEBP / MP4', uploadHint: 'Max. 50 MB · Min. 1200×1200px', artworkTitleLabel: 'Kunstwerktitel', artworkTitlePlaceholder: 'z.B. Auflösungsstudie III', tickerLabel: 'Token-Ticker', tickerHint: 'auto-generiert · bearbeitbar', categoryLabel: 'Kategorie', descriptionLabel: 'Beschreibung', descriptionPlaceholder: 'Beschreiben Sie Ihr Kunstwerk…', bondingCurveTypeLabel: 'Bonding-Kurventyp', totalSupplyLabel: 'Gesamtangebot', initPriceLabel: 'Anfangspreis (ETH)', creatorRoyaltyLabel: 'Creator-Lizenzgebühren', aiModeration: 'KI-Moderation…', launchArtwork: '✦ Kunstwerk launchen', previewLabel: 'Vorschau', curveLabel: '{type}-Kurve', initPriceCard: 'Anfangspreis', supplyCard: 'Angebot', royaltyCard: 'Lizenzgebühren', bondingCurveChart: 'Bonding-Kurve', priceVsSupply: 'Preis vs. Angebot', supply80: '80% Angebot', targetPrice: 'Zielpreis', at80Supply: 'bei 80% Angebot', ethToGrad: 'ETH bis Graduierung', graduationThreshold: 'Graduierungsschwelle', estGasCost: 'Geschätzte Gaskosten', deployDesc: 'auf Base deployen · {type}-Kurve', launchChecklist: 'Launch-Checkliste', stepUpload: 'Kunstwerk hochladen', stepTitle: 'Titel & Beschreibung', stepTicker: 'Token-Ticker festlegen', stepCategory: 'Kategorie wählen', stepCurve: 'Kurve konfigurieren', stepAiCheck: 'KI-Prüfung', stepWallet: 'Wallet verbinden', stepGas: 'Ausreichend Gasguthaben', stepDeploy: 'Auf Base deployen', awaitingSubmission: 'Warte auf Einreichung…', aiCheckDescription: 'KI prüft IP-Konflikte, verbotene Inhalte und Qualitätsstandards.', analyzing: 'Kunstwerk wird analysiert…', approved: 'Genehmigt — Bereit zum Launchen', approvedDetails: 'Keine IP-Konflikte · Standards erfüllt · Qualität OK', rejected: 'Abgelehnt', rejectedMessage: 'Möglicher IP-Konflikt erkannt. Überprüfen und erneut einreichen.', breadcrumbStudio: 'Studio', breadcrumbNew: 'Neues Kunstwerk', connected: 'Verbunden: {addr}', notConnected: 'Nicht verbunden' },
  vault: { portfolioValue: 'Portfoliowert', timeframe7d: '7T', timeframe30d: '30T', timeframe90d: '90T', allocation: 'Allokation', total: 'Gesamt', portfolioValueStat: 'Portfoliowert', unrealizedPnl: 'Nicht realisierter G&V', realizedPnl: 'Realisierter G&V', ethBalance: 'ETH-Guthaben', myHoldings: 'Meine Bestände', txHistory: 'TX-Verlauf', asset: 'Asset', qty: 'Menge', avgBuy: 'Ø Kaufpreis', current: 'Aktuell', value: 'Wert', pnl: 'G&V', chgPct: 'Änd. %', date: 'Datum', side: 'Seite', token: 'Token', ethSpent: 'ETH ausgegeben', buy: 'Kaufen', sell: 'Verkaufen', realizedPnlClosed: 'Realisierter G&V (geschlossen)', tradeLink: 'Handeln →', noResults: 'Keine Ergebnisse' },
  settings: { title: 'Einstellungen', accountSettings: 'Kontoeinstellungen', accountSettingsDesc: 'Verwalten Sie Ihr Profil, Sicherheit und Präferenzen.', profileSection: 'Profil', usernameLabel: 'Benutzername', usernamePlaceholder: 'Ihr_Benutzername', bioLabel: 'Bio', bioPlaceholder: 'Stellen Sie sich der Welt vor…', saving: 'Speichert…', saved: '✓ Gespeichert', saveChanges: 'Änderungen speichern', notificationsSection: 'Benachrichtigungen', tradeAlerts: 'Trade-Benachrichtigungen', tradeAlertsDesc: 'Benachrichtigt werden wenn Kunstwerke gehandelt werden', newFollowers: 'Neue Follower', newFollowersDesc: 'Wenn jemand Ihrem Profil folgt', priceMilestones: 'Preis-Meilensteine', priceMilestonesDesc: 'Wenn ein Kunstwerk ein Preisziel erreicht', securitySection: 'Sicherheit', authMethod: 'Auth.-Methode', authMethodDesc: 'Wie Sie sich bei ArtCurve anmelden', session: 'Sitzung', sessionDesc: 'Sie sind derzeit angemeldet', active: 'Aktiv', dangerZone: 'Gefahrenzone', signOut: 'Abmelden', signOutDesc: 'Von Ihrem Konto auf diesem Gerät abmelden' },
  wallet: { signInTitle: 'Melden Sie sich an, um Ihre Wallet zu sehen', signInDesc: 'Verbinden Sie sich mit GitHub, X oder einer Krypto-Wallet.', title: 'Wallet', yourWallet: 'Ihre Wallet', walletDesc: 'Verwalten Sie Ihre Identität, Guthaben und On-Chain-Aktivität.', verified: 'Verifiziert', anonymous: 'Anonym', signOut: 'Abmelden', connectedWallet: 'Verbundene Wallet', accountAddress: 'Kontoadresse', smartAccount: 'Smart Account · von Plattform verwaltet', copy: 'Kopieren', copied: 'Kopiert', explorer: 'Explorer', ethBalance: 'ETH-Guthaben', emptyWallet: 'Leere Wallet', walletNotConnected: 'Wallet nicht verbunden', portfolio: 'Portfolio', noPositions: 'Keine Positionen', holdingsCount: '{count} Bestand', holdingsCountPlural: '{count} Bestände', network: 'Netzwerk', authMethod: 'Auth.-Methode', portfolioHoldings: 'Portfolio-Bestände', totalPnl: 'Gesamt G&V:', linkWalletTitle: 'Externe Wallet verknüpfen', linkWalletDesc: 'Verbinden Sie MetaMask oder eine andere Wallet für On-Chain-Transaktionen.', noWalletsDetected: 'Keine Wallets gefunden', noWalletsHint: 'Installieren Sie MetaMask oder eine andere Browser-Erweiterung', getMetaMask: 'MetaMask holen', showLess: 'Weniger anzeigen', showMore: '{count} weitere Wallets', detected: 'Erkannt', securitySection: 'Sicherheit', signInMethod: 'Anmeldemethode', walletVerification: 'Wallet-Verifizierung', onChainWallet: 'On-Chain-Wallet (SIWE)', verifiedViaSiwe: 'Via EIP-4361 verifiziert', notVerified: 'Nicht verifiziert', accountRole: 'Kontorolle', artist: 'Künstler — kann Kunstwerke minten', admin: 'Administrator', collector: 'Sammler', userId: 'Benutzer-ID' },
  artwork: { backToMarketplace: 'Zurück zum Marktplatz', marketCap: 'Marktkapitalisierung', change24h: '24h-Änderung', holders: 'Inhaber', volume24h: 'Volumen 24h', completion: 'Fertigstellung', phase: 'Phase', graduated: '✦ Graduiert', bondingCurve: 'Bonding-Kurve', priceVsSupply: 'Preis vs. Angebot', now: 'jetzt', buy: '{ticker} kaufen', collectorVoices: 'Stimmen der Sammler', poor: 'Schlecht', fair: 'Mäßig', good: 'Gut', great: 'Sehr gut', exceptional: 'Hervorragend', sharePerspective: 'Teilen Sie Ihre Perspektive zu diesem Werk…', posting: 'Veröffentliche…', post: 'Veröffentlichen', connectToShare: 'Verbinden Sie Ihre Wallet, um zu teilen.', connect: 'Verbinden', noPerspectives: 'Noch keine Perspektiven.', artworkNotFound: 'Kunstwerk nicht gefunden', topHolders: 'Top-Inhaber' },
  error: { systemError: 'Systemfehler', somethingWentWrong: 'Etwas ist schiefgelaufen', tryAgain: 'Erneut versuchen' },
  notFound: { label: 'Seite nicht gefunden', description: 'Diese Kurve existiert nicht — oder wurde noch nicht deployt.', returnToMarket: 'Zurück zum Markt' },
  auth: { signingIn: 'Anmelden…' },
}

export default de
