import type { Translations } from './en'

const es: Translations = {
  nav: { marketplace: 'Mercado', trade: 'Intercambio', live: 'En vivo', guild: 'Gremio', vault: 'Bóveda', studio: 'Estudio' },
  header: { notifications: 'Notificaciones', markAllRead: 'Marcar todo como leído', allCaughtUp: 'Sin notificaciones nuevas', viewAllActivity: 'Ver toda la actividad', clearAll: 'Borrar todo', all: 'Todos', unread: 'No leídos', signOut: 'Cerrar sesión', connectWallet: 'Conectar billetera' },
  lang: { label: 'Idioma', search: 'Buscar idioma…' },
  common: { viewDetailReviews: 'Ver detalles y reseñas', buy: 'Comprar', sell: 'Vender', collect: 'Coleccionar', noReviewsYet: 'Sin reseñas aún', loading: 'Cargando…', error: 'Algo salió mal', search: 'Buscar…', noResults: 'Sin resultados', live: 'En vivo', back: 'Volver', cancel: 'Cancelar', confirm: 'Confirmar' },
  marketplace: { title: 'Mercado en vivo', subtitle: 'Intercambia obras únicas en la curva de bonding.', totalVolume: 'Volumen total', listings: 'Listados activos', trades24h: 'Intercambios 24H', all: 'Todos', search: 'Buscar…', race: 'Carrera', marketCap: 'Cap. de mercado', change24h: 'Cambio 24h', change7d: 'Cambio 7d', liveActivity: 'Actividad en vivo' },
  trade: { markets: 'Mercados', search: 'Buscar…', change24h: 'Cambio 24H', vol24h: 'Vol. 24H', high24h: 'Máx. 24H', low24h: 'Mín. 24H', holders: 'Poseedores', progress: 'Progreso', recentTrades: 'Intercambios recientes', orderBook: 'Libro de órdenes', time: 'Tiempo', side: 'Lado', price: 'Precio', size: 'Cant.', sizeEth: 'Cant. (ETH)', total: 'Total', wallet: 'Billetera', priceEth: 'Precio (ETH)', bal: 'Saldo', max: 'MÁX', youPay: 'Pagas', youReceive: 'Recibes', estimate: 'estimado', impact: 'Impacto', minOut: 'Mín. recibido', graduationWarning: 'Esta operación graduaría la obra al DEX', youSell: 'Vendes', slippage: 'Deslizamiento', confirming: 'Confirmando…', orderExecuted: 'Orden ejecutada', noResults: 'Sin resultados' },
  guild: { joined: 'Unido', guilds: 'Gremios', discover: 'Descubrir', myGuilds: 'Mis gremios', statsFormat: '{count} gremios · {members} miembros', createGuild: '+ Crear gremio', createModalTitle: 'Crear un gremio', guildNameLabel: 'Nombre del gremio', guildNamePlaceholder: 'ej. La Sociedad Nocturna', descriptionLabel: 'Descripción', descriptionPlaceholder: '¿Qué colecciona y celebra tu gremio?', focusLabel: 'Enfoque', createButton: '✦ Crear gremio', activity: 'Actividad', chat: 'Chat', members: 'Miembros', holdings: 'Tenencias', leave: 'Salir', joinGuild: 'Unirse', reply: 'Responder', chatPlaceholder: 'Mensaje a {name}…', collectiveHoldings: 'Tenencias colectivas', positions: 'Posiciones', noHoldingsData: 'Sin datos colectivos', moreMembers: '+{count} miembros más', tokens: '{count} tokens', qty: 'cant.', pctCollective: '% del colectivo' },
  live: { home: 'Inicio', live: 'En vivo', artists: 'Artistas', you: 'Tú', all: 'Todos', following: 'Siguiendo', videos: 'Videos', painting: 'Pintura', drawing: 'Dibujo', digital: 'Digital', sculpture: 'Escultura', mixedMedia: 'Mixto', trending: 'Tendencia', watching: '{count} viendo', saveToPlaylist: 'Guardar en lista', share: 'Compartir', report: 'Reportar', moreOptions: 'Más opciones', goLive: 'Transmitir', streamTitleLabel: 'Título del stream', streamTitlePlaceholder: '¿Qué estás creando hoy?', categoryLabel: 'Categoría', starting: 'Iniciando…', startStreaming: '● Comenzar', goLiveButton: 'Transmitir', noContent: 'Sin contenido en esta categoría' },
  studio: { createArtwork: 'Crear obra', uploadPrompt: 'Subir obra · JPG / PNG / WEBP / MP4', uploadHint: 'Máx 50 MB · Mín 1200×1200px', artworkTitleLabel: 'Título de la obra', artworkTitlePlaceholder: 'ej. Estudio III', tickerLabel: 'Ticker', tickerHint: 'auto-generado · editable', categoryLabel: 'Categoría', descriptionLabel: 'Descripción', descriptionPlaceholder: 'Describe tu obra…', bondingCurveTypeLabel: 'Tipo de curva', totalSupplyLabel: 'Oferta total', initPriceLabel: 'Precio inicial (ETH)', creatorRoyaltyLabel: 'Regalías del creador', aiModeration: 'Moderación IA…', launchArtwork: '✦ Lanzar obra', previewLabel: 'Vista previa', curveLabel: 'curva {type}', initPriceCard: 'Precio inicial', supplyCard: 'Oferta', royaltyCard: 'Regalías', bondingCurveChart: 'Curva de bonding', priceVsSupply: 'precio vs. oferta', supply80: '80% oferta', targetPrice: 'Precio objetivo', at80Supply: 'al 80% de oferta', ethToGrad: 'ETH para graduación', graduationThreshold: 'umbral de graduación', estGasCost: 'Gas estimado', deployDesc: 'desplegar en Base · curva {type}', launchChecklist: 'Lista de lanzamiento', stepUpload: 'Subir obra', stepTitle: 'Título y descripción', stepTicker: 'Definir ticker', stepCategory: 'Elegir categoría', stepCurve: 'Configurar curva', stepAiCheck: 'Verificación IA', stepWallet: 'Conectar billetera', stepGas: 'Saldo gas suficiente', stepDeploy: 'Desplegar', awaitingSubmission: 'Esperando envío…', aiCheckDescription: 'La IA verifica conflictos IP y estándares.', analyzing: 'Analizando obra…', approved: 'Aprobado — Listo para lanzar', approvedDetails: 'Sin conflictos IP · Estándares OK', rejected: 'Rechazado', rejectedMessage: 'Conflicto IP potencial detectado.', breadcrumbStudio: 'Estudio', breadcrumbNew: 'Nueva obra', connected: 'Conectado: {addr}', notConnected: 'No conectado' },
  vault: { portfolioValue: 'Valor del portafolio', timeframe7d: '7D', timeframe30d: '30D', timeframe90d: '90D', allocation: 'Asignación', total: 'Total', portfolioValueStat: 'Valor del portafolio', unrealizedPnl: 'P&L no realizado', realizedPnl: 'P&L realizado', ethBalance: 'Saldo ETH', myHoldings: 'Mis tenencias', txHistory: 'Historial TX', asset: 'Activo', qty: 'Cant.', avgBuy: 'Precio prom.', current: 'Actual', value: 'Valor', pnl: 'P&L', chgPct: 'Var. %', date: 'Fecha', side: 'Lado', token: 'Token', ethSpent: 'ETH gastado', buy: 'Comprar', sell: 'Vender', realizedPnlClosed: 'P&L realizado (cerradas)', tradeLink: 'Intercambiar →', noResults: 'Sin resultados' },
  settings: { title: 'Configuración', accountSettings: 'Configuración de cuenta', accountSettingsDesc: 'Gestiona tu perfil, seguridad y preferencias.', profileSection: 'Perfil', usernameLabel: 'Nombre de usuario', usernamePlaceholder: 'tu_usuario', bioLabel: 'Bio', bioPlaceholder: 'Cuéntale al mundo sobre ti…', saving: 'Guardando…', saved: '✓ Guardado', saveChanges: 'Guardar cambios', notificationsSection: 'Notificaciones', tradeAlerts: 'Alertas de intercambio', tradeAlertsDesc: 'Notificado cuando tus obras sean intercambiadas', newFollowers: 'Nuevos seguidores', newFollowersDesc: 'Cuando alguien sigue tu perfil', priceMilestones: 'Hitos de precio', priceMilestonesDesc: 'Cuando una obra alcanza un objetivo de precio', securitySection: 'Seguridad', authMethod: 'Método de autenticación', authMethodDesc: 'Cómo inicias sesión en ArtCurve', session: 'Sesión', sessionDesc: 'Actualmente conectado', active: 'Activo', dangerZone: 'Zona de peligro', signOut: 'Cerrar sesión', signOutDesc: 'Cierra sesión en este dispositivo' },
  wallet: { signInTitle: 'Inicia sesión para ver tu billetera', signInDesc: 'Conéctate con GitHub, X o una billetera crypto.', title: 'Billetera', yourWallet: 'Tu billetera', walletDesc: 'Gestiona tu identidad, saldo y actividad on-chain.', verified: 'Verificado', anonymous: 'Anónimo', signOut: 'Cerrar sesión', connectedWallet: 'Billetera conectada', accountAddress: 'Dirección de cuenta', smartAccount: 'Cuenta inteligente · gestionada por la plataforma', copy: 'Copiar', copied: 'Copiado', explorer: 'Explorador', ethBalance: 'Saldo ETH', emptyWallet: 'Billetera vacía', walletNotConnected: 'Billetera no conectada', portfolio: 'Portafolio', noPositions: 'Sin posiciones', holdingsCount: '{count} tenencia', holdingsCountPlural: '{count} tenencias', network: 'Red', authMethod: 'Método de auth.', portfolioHoldings: 'Tenencias del portafolio', totalPnl: 'P&L total:', linkWalletTitle: 'Vincular billetera externa', linkWalletDesc: 'Conecta MetaMask u otra billetera para operar on-chain.', noWalletsDetected: 'No se detectaron billeteras', noWalletsHint: 'Instala MetaMask u otra extensión', getMetaMask: 'Obtener MetaMask', showLess: 'Mostrar menos', showMore: 'Ver {count} billeteras más', detected: 'Detectado', securitySection: 'Seguridad', signInMethod: 'Método de inicio de sesión', walletVerification: 'Verificación de billetera', onChainWallet: 'Billetera On-Chain (SIWE)', verifiedViaSiwe: 'Verificado via EIP-4361', notVerified: 'No verificado', accountRole: 'Rol de cuenta', artist: 'Artista — puede crear obras', admin: 'Administrador', collector: 'Coleccionista', userId: 'ID de usuario' },
  artwork: { backToMarketplace: 'Volver al mercado', marketCap: 'Cap. de mercado', change24h: 'Cambio 24h', holders: 'Poseedores', volume24h: 'Volumen 24h', completion: 'Finalización', phase: 'Fase', graduated: '✦ Graduado', bondingCurve: 'Curva de bonding', priceVsSupply: 'precio vs. oferta', now: 'ahora', buy: 'Comprar {ticker}', collectorVoices: 'Voces de coleccionistas', poor: 'Pobre', fair: 'Regular', good: 'Bueno', great: 'Muy bueno', exceptional: 'Excepcional', sharePerspective: 'Comparte tu perspectiva sobre esta obra…', posting: 'Publicando…', post: 'Publicar', connectToShare: 'Conecta tu billetera para compartir.', connect: 'Conectar', noPerspectives: 'Sin perspectivas aún.', artworkNotFound: 'Obra no encontrada', topHolders: 'Principales poseedores' },
  error: { systemError: 'Error del sistema', somethingWentWrong: 'Algo salió mal', tryAgain: 'Intentar de nuevo' },
  notFound: { label: 'Página no encontrada', description: 'Esta curva no existe — o aún no ha sido desplegada.', returnToMarket: 'Volver al mercado' },
  auth: { signingIn: 'Iniciando sesión…' },
}

export default es
