import type { Translations } from './en'

const fr: Translations = {
  nav: { marketplace: 'Marché', trade: 'Échange', live: 'En direct', guild: 'Guilde', vault: 'Coffre', studio: 'Studio' },
  header: { notifications: 'Notifications', markAllRead: 'Tout marquer comme lu', allCaughtUp: 'Aucune nouvelle notification', viewAllActivity: "Voir toute l'activité", clearAll: 'Tout effacer', all: 'Tout', unread: 'Non lus', signOut: 'Déconnexion', connectWallet: 'Connecter le portefeuille' },
  lang: { label: 'Langue', search: 'Rechercher une langue…' },
  common: { viewDetailReviews: 'Voir les détails & avis', buy: 'Acheter', sell: 'Vendre', collect: 'Collecter', noReviewsYet: "Aucun avis pour l'instant", loading: 'Chargement…', error: "Une erreur s'est produite", search: 'Rechercher…', noResults: 'Aucun résultat', live: 'En direct', back: 'Retour', cancel: 'Annuler', confirm: 'Confirmer' },
  marketplace: { title: 'Marché en direct', subtitle: 'Échangez des œuvres uniques sur la courbe de liaison.', totalVolume: 'Volume total', listings: 'Annonces actives', trades24h: 'Échanges 24H', all: 'Tout', search: 'Rechercher…', race: 'Course', marketCap: 'Capitalisation', change24h: 'Variation 24h', change7d: 'Variation 7j', liveActivity: 'Activité en direct' },
  trade: { markets: 'Marchés', search: 'Rechercher…', change24h: 'Variation 24H', vol24h: 'Vol. 24H', high24h: 'Haut 24H', low24h: 'Bas 24H', holders: 'Détenteurs', progress: 'Progression', recentTrades: "Échanges récents", orderBook: "Carnet d'ordres", time: 'Heure', side: 'Côté', price: 'Prix', size: 'Qté', sizeEth: 'Qté (ETH)', total: 'Total', wallet: 'Portefeuille', priceEth: 'Prix (ETH)', bal: 'Solde', max: 'MAX', youPay: 'Vous payez', youReceive: 'Vous recevez', estimate: 'estimation', impact: 'Impact', minOut: 'Min. reçu', graduationWarning: "Cette transaction ferait passer l'œuvre sur DEX", youSell: 'Vous vendez', slippage: 'Glissement', confirming: 'Confirmation…', orderExecuted: 'Ordre exécuté', noResults: 'Aucun résultat' },
  guild: { joined: 'Rejoint', guilds: 'Guildes', discover: 'Découvrir', myGuilds: 'Mes guildes', statsFormat: '{count} guildes · {members} membres', createGuild: '+ Créer une guilde', createModalTitle: 'Créer une guilde', guildNameLabel: 'Nom de la guilde', guildNamePlaceholder: 'ex. La Société Nocturne', descriptionLabel: 'Description', descriptionPlaceholder: 'Que collecte et célèbre votre guilde?', focusLabel: 'Thème', createButton: '✦ Créer la guilde', activity: 'Activité', chat: 'Discussion', members: 'Membres', holdings: 'Avoirs', leave: 'Quitter', joinGuild: 'Rejoindre', reply: 'Répondre', chatPlaceholder: 'Message {name}…', collectiveHoldings: 'Avoirs collectifs', positions: 'Positions', noHoldingsData: 'Aucune donnée collective', moreMembers: '+{count} autres membres', tokens: '{count} tokens', qty: 'qté', pctCollective: '% du collectif' },
  live: { home: 'Accueil', live: 'En direct', artists: 'Artistes', you: 'Vous', all: 'Tout', following: 'Abonnements', videos: 'Vidéos', painting: 'Peinture', drawing: 'Dessin', digital: 'Numérique', sculpture: 'Sculpture', mixedMedia: 'Mixte', trending: 'Tendance', watching: '{count} spectateurs', saveToPlaylist: 'Sauvegarder', share: 'Partager', report: 'Signaler', moreOptions: "Plus d'options", goLive: 'Diffuser', streamTitleLabel: 'Titre du stream', streamTitlePlaceholder: "Que créez-vous aujourd'hui?", categoryLabel: 'Catégorie', starting: 'Démarrage…', startStreaming: '● Commencer', goLiveButton: 'Diffuser', noContent: 'Aucun contenu dans cette catégorie' },
  studio: { createArtwork: 'Créer une œuvre', uploadPrompt: 'Déposer · JPG / PNG / WEBP / MP4', uploadHint: 'Max 50 Mo · Min 1200×1200px', artworkTitleLabel: "Titre de l'œuvre", artworkTitlePlaceholder: 'ex. Étude III', tickerLabel: 'Ticker', tickerHint: 'généré auto · modifiable', categoryLabel: 'Catégorie', descriptionLabel: 'Description', descriptionPlaceholder: 'Décrivez votre œuvre…', bondingCurveTypeLabel: 'Type de courbe', totalSupplyLabel: 'Offre totale', initPriceLabel: 'Prix initial (ETH)', creatorRoyaltyLabel: 'Royalties', aiModeration: 'Modération IA…', launchArtwork: "✦ Lancer l'œuvre", previewLabel: 'Aperçu', curveLabel: 'courbe {type}', initPriceCard: 'Prix initial', supplyCard: 'Offre', royaltyCard: 'Royalties', bondingCurveChart: 'Courbe de liaison', priceVsSupply: 'prix vs. offre', supply80: '80% offre', targetPrice: 'Prix cible', at80Supply: "à 80% d'offre", ethToGrad: 'ETH diplôme', graduationThreshold: 'seuil', estGasCost: 'Gas estimé', deployDesc: 'déployer sur Base · courbe {type}', launchChecklist: 'Liste de lancement', stepUpload: 'Téléverser', stepTitle: 'Titre & description', stepTicker: 'Définir le ticker', stepCategory: 'Catégorie', stepCurve: 'Configurer la courbe', stepAiCheck: 'Vérification IA', stepWallet: 'Connecter portefeuille', stepGas: 'Solde gas suffisant', stepDeploy: 'Déployer', awaitingSubmission: 'En attente…', aiCheckDescription: "L'IA vérifie les conflits IP et standards.", analyzing: "Analyse de l'œuvre…", approved: 'Approuvé — Prêt', approvedDetails: 'Pas de conflit IP · Standards OK', rejected: 'Refusé', rejectedMessage: 'Conflit IP potentiel détecté.', breadcrumbStudio: 'Studio', breadcrumbNew: 'Nouvelle œuvre', connected: 'Connecté: {addr}', notConnected: 'Non connecté' },
  vault: { portfolioValue: 'Valeur du portfolio', timeframe7d: '7J', timeframe30d: '30J', timeframe90d: '90J', allocation: 'Allocation', total: 'Total', portfolioValueStat: 'Valeur du portfolio', unrealizedPnl: 'P&L non réalisé', realizedPnl: 'P&L réalisé', ethBalance: 'Solde ETH', myHoldings: 'Mes avoirs', txHistory: 'Historique TX', asset: 'Actif', qty: 'Qté', avgBuy: 'Prix moy.', current: 'Actuel', value: 'Valeur', pnl: 'P&L', chgPct: 'Var. %', date: 'Date', side: 'Côté', token: 'Token', ethSpent: 'ETH dépensé', buy: 'Acheter', sell: 'Vendre', realizedPnlClosed: 'P&L réalisé (fermées)', tradeLink: 'Échanger →', noResults: 'Aucun résultat' },
  settings: { title: 'Paramètres', accountSettings: 'Paramètres du compte', accountSettingsDesc: 'Gérez votre profil, sécurité et préférences.', profileSection: 'Profil', usernameLabel: "Nom d'utilisateur", usernamePlaceholder: 'votre_pseudo', bioLabel: 'Bio', bioPlaceholder: 'Présentez-vous…', saving: 'Sauvegarde…', saved: '✓ Sauvegardé', saveChanges: 'Sauvegarder', notificationsSection: 'Notifications', tradeAlerts: "Alertes d'échange", tradeAlertsDesc: 'Notifié quand vos œuvres sont échangées', newFollowers: 'Nouveaux abonnés', newFollowersDesc: 'Quand quelqu\'un suit votre profil', priceMilestones: 'Jalons de prix', priceMilestonesDesc: "Quand une œuvre atteint un objectif", securitySection: 'Sécurité', authMethod: "Méthode d'auth.", authMethodDesc: 'Comment vous connectez-vous à ArtCurve', session: 'Session', sessionDesc: 'Vous êtes connecté', active: 'Actif', dangerZone: 'Zone dangereuse', signOut: 'Déconnexion', signOutDesc: 'Déconnectez-vous sur cet appareil' },
  wallet: { signInTitle: 'Connectez-vous pour voir votre portefeuille', signInDesc: 'Connectez-vous avec GitHub, X ou un portefeuille crypto.', title: 'Portefeuille', yourWallet: 'Votre portefeuille', walletDesc: 'Gérez votre identité, solde et activité on-chain.', verified: 'Vérifié', anonymous: 'Anonyme', signOut: 'Déconnexion', connectedWallet: 'Portefeuille connecté', accountAddress: 'Adresse du compte', smartAccount: 'Compte intelligent · géré par la plateforme', copy: 'Copier', copied: 'Copié', explorer: 'Explorateur', ethBalance: 'Solde ETH', emptyWallet: 'Portefeuille vide', walletNotConnected: 'Portefeuille non connecté', portfolio: 'Portfolio', noPositions: 'Aucune position', holdingsCount: '{count} avoir', holdingsCountPlural: '{count} avoirs', network: 'Réseau', authMethod: "Méthode d'auth.", portfolioHoldings: 'Avoirs du portfolio', totalPnl: 'P&L total:', linkWalletTitle: 'Lier un portefeuille externe', linkWalletDesc: 'Connectez MetaMask ou un autre portefeuille.', noWalletsDetected: 'Aucun portefeuille détecté', noWalletsHint: 'Installez MetaMask ou une autre extension', getMetaMask: 'Obtenir MetaMask', showLess: 'Réduire', showMore: 'Voir {count} autres', detected: 'Détecté', securitySection: 'Sécurité', signInMethod: 'Méthode de connexion', walletVerification: 'Vérification du portefeuille', onChainWallet: 'Portefeuille On-Chain (SIWE)', verifiedViaSiwe: 'Vérifié via EIP-4361', notVerified: 'Non vérifié', accountRole: 'Rôle', artist: 'Artiste — peut créer des œuvres', admin: 'Administrateur', collector: 'Collectionneur', userId: 'ID utilisateur' },
  artwork: { backToMarketplace: 'Retour au marché', marketCap: 'Capitalisation', change24h: 'Variation 24h', holders: 'Détenteurs', volume24h: 'Volume 24h', completion: 'Achèvement', phase: 'Phase', graduated: '✦ Diplômé', bondingCurve: 'Courbe de liaison', priceVsSupply: 'prix vs. offre', now: 'maintenant', buy: 'Acheter {ticker}', collectorVoices: 'Voix des collectionneurs', poor: 'Mauvais', fair: 'Passable', good: 'Bon', great: 'Très bon', exceptional: 'Exceptionnel', sharePerspective: 'Partagez votre perspective…', posting: 'Publication…', post: 'Publier', connectToShare: 'Connectez votre portefeuille pour partager.', connect: 'Connecter', noPerspectives: 'Aucune perspective.', artworkNotFound: 'Œuvre introuvable', topHolders: 'Principaux détenteurs' },
  error: { systemError: 'Erreur système', somethingWentWrong: "Une erreur s'est produite", tryAgain: 'Réessayer' },
  notFound: { label: 'Page introuvable', description: "Cette courbe n'existe pas — ou n'a pas été déployée.", returnToMarket: 'Retour au marché' },
  auth: { signingIn: 'Connexion…' },
}

export default fr
