import type { Translations } from './en'

const ja: Translations = {
  nav: { marketplace: 'マーケット', trade: 'トレード', live: 'ライブ', guild: 'ギルド', vault: 'ボールト', studio: 'スタジオ' },
  header: { notifications: '通知', markAllRead: 'すべて既読にする', allCaughtUp: '新しい通知はありません', viewAllActivity: 'すべてのアクティビティを表示', clearAll: 'すべてクリア', all: 'すべて', unread: '未読', signOut: 'サインアウト', connectWallet: 'ウォレット接続' },
  lang: { label: '言語', search: '言語を検索…' },
  common: { viewDetailReviews: '詳細とレビューを見る', buy: '購入', sell: '売却', collect: 'コレクト', noReviewsYet: 'まだレビューはありません', loading: '読み込み中…', error: 'エラーが発生しました', search: '検索…', noResults: '結果なし', live: 'ライブ', back: '戻る', cancel: 'キャンセル', confirm: '確認' },
  marketplace: { title: 'ライブマーケット', subtitle: 'ボンディングカーブでユニークな作品を取引。', totalVolume: '総取引量', listings: 'リスト中', trades24h: '24H取引', all: 'すべて', search: '検索…', race: 'レース', marketCap: '時価総額', change24h: '24h変動', change7d: '7d変動', liveActivity: 'ライブアクティビティ' },
  trade: { markets: 'マーケット', search: '検索…', change24h: '24H変動', vol24h: '24H出来高', high24h: '24H高値', low24h: '24H安値', holders: '保有者', progress: '進捗', recentTrades: '最近の取引', orderBook: '注文板', time: '時間', side: 'サイド', price: '価格', size: '数量', sizeEth: '数量(ETH)', total: '合計', wallet: 'ウォレット', priceEth: '価格(ETH)', bal: '残高', max: '最大', youPay: '支払い', youReceive: '受取り', estimate: '概算', impact: 'インパクト', minOut: '最低受取', graduationWarning: 'この取引でアートワークがDEXに卒業します', youSell: '売却', slippage: 'スリッページ', confirming: '確認中…', orderExecuted: '注文完了', noResults: '結果なし' },
  guild: { joined: '参加済み', guilds: 'ギルド', discover: '発見', myGuilds: 'マイギルド', statsFormat: '{count}ギルド · {members}メンバー', createGuild: '+ ギルド作成', createModalTitle: 'ギルドを作成', guildNameLabel: 'ギルド名', guildNamePlaceholder: '例: ノクターン協会', descriptionLabel: '説明', descriptionPlaceholder: 'ギルドは何を収集・祝いますか?', focusLabel: 'フォーカス', createButton: '✦ ギルドを作成', activity: 'アクティビティ', chat: 'チャット', members: 'メンバー', holdings: '保有', leave: '退会', joinGuild: 'ギルドに参加', reply: '返信', chatPlaceholder: '{name}にメッセージ…', collectiveHoldings: '共同保有', positions: 'ポジション', noHoldingsData: '共同保有データなし', moreMembers: '+{count}人のメンバー', tokens: '{count}トークン', qty: '数量', pctCollective: '% 共同' },
  live: { home: 'ホーム', live: 'ライブ', artists: 'アーティスト', you: 'あなた', all: 'すべて', following: 'フォロー中', videos: '動画', painting: '絵画', drawing: 'デッサン', digital: 'デジタル', sculpture: '彫刻', mixedMedia: 'ミクスドメディア', trending: 'トレンド', watching: '{count}人が視聴中', saveToPlaylist: 'プレイリストに保存', share: 'シェア', report: '報告', moreOptions: 'その他', goLive: 'ライブ配信', streamTitleLabel: 'タイトル', streamTitlePlaceholder: '今日は何を作っていますか?', categoryLabel: 'カテゴリ', starting: '開始中…', startStreaming: '● 配信開始', goLiveButton: 'ライブ配信', noContent: 'このカテゴリにコンテンツはありません' },
  studio: { createArtwork: 'アートワーク作成', uploadPrompt: 'ドロップ · JPG / PNG / WEBP / MP4', uploadHint: '最大50MB · 最小1200×1200px', artworkTitleLabel: 'タイトル', artworkTitlePlaceholder: '例: 解体研究 III', tickerLabel: 'ティッカー', tickerHint: '自動生成 · 編集可', categoryLabel: 'カテゴリ', descriptionLabel: '説明', descriptionPlaceholder: 'アートワークを説明してください…', bondingCurveTypeLabel: 'ボンディングカーブタイプ', totalSupplyLabel: '総供給量', initPriceLabel: '初期価格(ETH)', creatorRoyaltyLabel: 'クリエイターロイヤリティ', aiModeration: 'AIモデレーション中…', launchArtwork: '✦ アートワーク公開', previewLabel: 'プレビュー', curveLabel: '{type}カーブ', initPriceCard: '初期価格', supplyCard: '供給量', royaltyCard: 'ロイヤリティ', bondingCurveChart: 'ボンディングカーブ', priceVsSupply: '価格 vs. 供給', supply80: '80%供給', targetPrice: '目標価格', at80Supply: '供給80%時', ethToGrad: '卒業ETH', graduationThreshold: '卒業閾値', estGasCost: '推定ガス代', deployDesc: 'Baseにデプロイ · {type}カーブ', launchChecklist: 'ローンチチェックリスト', stepUpload: 'アップロード', stepTitle: 'タイトル & 説明', stepTicker: 'ティッカー設定', stepCategory: 'カテゴリ選択', stepCurve: 'カーブ設定', stepAiCheck: 'AIチェック', stepWallet: 'ウォレット接続', stepGas: 'ガス残高確認', stepDeploy: 'デプロイ', awaitingSubmission: '送信待ち…', aiCheckDescription: 'AIがIPとコンテンツをチェックします。', analyzing: '分析中…', approved: '承認済み — 公開準備OK', approvedDetails: 'IP問題なし · 基準OK', rejected: '却下', rejectedMessage: 'IPの問題が検出されました。', breadcrumbStudio: 'スタジオ', breadcrumbNew: '新作品', connected: '接続済み: {addr}', notConnected: '未接続' },
  vault: { portfolioValue: 'ポートフォリオ価値', timeframe7d: '7日', timeframe30d: '30日', timeframe90d: '90日', allocation: 'アロケーション', total: '合計', portfolioValueStat: 'ポートフォリオ価値', unrealizedPnl: '未実現損益', realizedPnl: '実現損益', ethBalance: 'ETH残高', myHoldings: '保有中', txHistory: '取引履歴', asset: '資産', qty: '数量', avgBuy: '平均購入価格', current: '現在', value: '価値', pnl: '損益', chgPct: '変動%', date: '日付', side: 'サイド', token: 'トークン', ethSpent: '使用ETH', buy: '購入', sell: '売却', realizedPnlClosed: '実現損益(決済済み)', tradeLink: '取引 →', noResults: '結果なし' },
  settings: { title: '設定', accountSettings: 'アカウント設定', accountSettingsDesc: 'プロフィール、セキュリティ、設定を管理。', profileSection: 'プロフィール', usernameLabel: 'ユーザー名', usernamePlaceholder: 'your_username', bioLabel: '自己紹介', bioPlaceholder: '自己紹介を書いてください…', saving: '保存中…', saved: '✓ 保存済み', saveChanges: '変更を保存', notificationsSection: '通知', tradeAlerts: '取引アラート', tradeAlertsDesc: 'アートワークが取引された時に通知', newFollowers: '新フォロワー', newFollowersDesc: '誰かがフォローした時', priceMilestones: '価格マイルストーン', priceMilestonesDesc: '価格目標に達した時', securitySection: 'セキュリティ', authMethod: '認証方法', authMethodDesc: 'ArtCurveへのサインイン方法', session: 'セッション', sessionDesc: 'サインイン済み', active: 'アクティブ', dangerZone: '危険ゾーン', signOut: 'サインアウト', signOutDesc: 'このデバイスからサインアウト' },
  wallet: { signInTitle: 'ウォレットを表示するにはサインインしてください', signInDesc: 'GitHub、X、またはウォレットで接続してください。', title: 'ウォレット', yourWallet: 'マイウォレット', walletDesc: 'アイデンティティ、残高、オンチェーン活動を管理。', verified: '認証済み', anonymous: '匿名', signOut: 'サインアウト', connectedWallet: '接続済みウォレット', accountAddress: 'アカウントアドレス', smartAccount: 'スマートアカウント · プラットフォーム管理', copy: 'コピー', copied: 'コピー済み', explorer: 'エクスプローラー', ethBalance: 'ETH残高', emptyWallet: '空のウォレット', walletNotConnected: 'ウォレット未接続', portfolio: 'ポートフォリオ', noPositions: 'ポジションなし', holdingsCount: '{count}保有', holdingsCountPlural: '{count}保有', network: 'ネットワーク', authMethod: '認証方法', portfolioHoldings: 'ポートフォリオ保有', totalPnl: '総損益:', linkWalletTitle: '外部ウォレットをリンク', linkWalletDesc: 'MetaMaskなどのウォレットを接続してオンチェーンで取引。', noWalletsDetected: 'ウォレットが検出されません', noWalletsHint: 'MetaMaskなどの拡張機能をインストール', getMetaMask: 'MetaMaskを入手', showLess: '折りたたむ', showMore: 'さらに{count}件のウォレット', detected: '検出済み', securitySection: 'セキュリティ', signInMethod: 'サインイン方法', walletVerification: 'ウォレット認証', onChainWallet: 'オンチェーンウォレット(SIWE)', verifiedViaSiwe: 'EIP-4361で認証済み', notVerified: '未認証', accountRole: 'アカウントロール', artist: 'アーティスト — ミント可能', admin: '管理者', collector: 'コレクター', userId: 'ユーザーID' },
  artwork: { backToMarketplace: 'マーケットに戻る', marketCap: '時価総額', change24h: '24h変動', holders: '保有者', volume24h: '24h出来高', completion: '達成率', phase: 'フェーズ', graduated: '✦ 卒業済み', bondingCurve: 'ボンディングカーブ', priceVsSupply: '価格 vs. 供給', now: '現在', buy: '{ticker}を購入', collectorVoices: 'コレクターの声', poor: '不可', fair: '可', good: '良', great: '優', exceptional: '秀', sharePerspective: 'この作品への視点を共有…', posting: '投稿中…', post: '投稿', connectToShare: '視点を共有するにはウォレットを接続。', connect: '接続', noPerspectives: 'まだ視点はありません。', artworkNotFound: 'アートワークが見つかりません', topHolders: 'トップ保有者' },
  error: { systemError: 'システムエラー', somethingWentWrong: 'エラーが発生しました', tryAgain: '再試行' },
  notFound: { label: 'ページが見つかりません', description: 'このカーブは存在しません — またはまだデプロイされていません。', returnToMarket: 'マーケットに戻る' },
  auth: { signingIn: 'サインイン中…' },
}

export default ja
