import type { Translations } from './en'

const ko: Translations = {
  nav: { marketplace: '마켓', trade: '거래', live: '라이브', guild: '길드', vault: '볼트', studio: '스튜디오' },
  header: { notifications: '알림', markAllRead: '모두 읽음으로 표시', allCaughtUp: '새 알림이 없습니다', viewAllActivity: '모든 활동 보기', clearAll: '모두 지우기', all: '전체', unread: '읽지 않음', signOut: '로그아웃', connectWallet: '지갑 연결' },
  lang: { label: '언어', search: '언어 검색…' },
  common: { viewDetailReviews: '상세 및 리뷰 보기', buy: '구매', sell: '판매', collect: '수집', noReviewsYet: '아직 리뷰가 없습니다', loading: '로딩 중…', error: '오류가 발생했습니다', search: '검색…', noResults: '결과 없음', live: '라이브', back: '뒤로', cancel: '취소', confirm: '확인' },
  marketplace: { title: '실시간 마켓', subtitle: '본딩 커브에서 독특한 작품을 거래하세요.', totalVolume: '총 거래량', listings: '상장 중', trades24h: '24H 거래', all: '전체', search: '검색…', race: '레이스', marketCap: '시가총액', change24h: '24h 변동', change7d: '7d 변동', liveActivity: '실시간 활동' },
  trade: { markets: '마켓', search: '검색…', change24h: '24H 변동', vol24h: '24H 거래량', high24h: '24H 고가', low24h: '24H 저가', holders: '보유자', progress: '진행률', recentTrades: '최근 거래', orderBook: '호가창', time: '시간', side: '방향', price: '가격', size: '수량', sizeEth: '수량(ETH)', total: '합계', wallet: '지갑', priceEth: '가격(ETH)', bal: '잔액', max: '최대', youPay: '지불', youReceive: '수령', estimate: '예상', impact: '영향', minOut: '최소 수령', graduationWarning: '이 거래로 작품이 DEX로 졸업됩니다', youSell: '판매', slippage: '슬리피지', confirming: '확인 중…', orderExecuted: '주문 체결', noResults: '결과 없음' },
  guild: { joined: '가입됨', guilds: '길드', discover: '탐색', myGuilds: '내 길드', statsFormat: '{count}개 길드 · {members}명', createGuild: '+ 길드 만들기', createModalTitle: '길드 만들기', guildNameLabel: '길드 이름', guildNamePlaceholder: '예: 녹턴 소사이어티', descriptionLabel: '설명', descriptionPlaceholder: '길드가 수집하고 기념하는 것은?', focusLabel: '주제', createButton: '✦ 길드 만들기', activity: '활동', chat: '채팅', members: '멤버', holdings: '보유', leave: '탈퇴', joinGuild: '길드 가입', reply: '답글', chatPlaceholder: '{name}에게 메시지…', collectiveHoldings: '공동 보유', positions: '포지션', noHoldingsData: '공동 보유 데이터 없음', moreMembers: '+{count}명 더', tokens: '{count}개 토큰', qty: '수량', pctCollective: '% 공동' },
  live: { home: '홈', live: '라이브', artists: '아티스트', you: '나', all: '전체', following: '팔로잉', videos: '영상', painting: '회화', drawing: '드로잉', digital: '디지털', sculpture: '조각', mixedMedia: '혼합 매체', trending: '트렌딩', watching: '{count}명 시청 중', saveToPlaylist: '재생목록에 저장', share: '공유', report: '신고', moreOptions: '더 보기', goLive: '라이브 시작', streamTitleLabel: '스트림 제목', streamTitlePlaceholder: '오늘 무엇을 만드나요?', categoryLabel: '카테고리', starting: '시작 중…', startStreaming: '● 방송 시작', goLiveButton: '라이브', noContent: '이 카테고리에 콘텐츠가 없습니다' },
  studio: { createArtwork: '작품 만들기', uploadPrompt: '작품 업로드 · JPG / PNG / WEBP / MP4', uploadHint: '최대 50MB · 최소 1200×1200px', artworkTitleLabel: '작품 제목', artworkTitlePlaceholder: '예: 해체 연구 III', tickerLabel: '티커', tickerHint: '자동 생성 · 편집 가능', categoryLabel: '카테고리', descriptionLabel: '설명', descriptionPlaceholder: '작품을 설명해 주세요…', bondingCurveTypeLabel: '본딩 커브 유형', totalSupplyLabel: '총 공급량', initPriceLabel: '초기 가격(ETH)', creatorRoyaltyLabel: '크리에이터 로열티', aiModeration: 'AI 검토 중…', launchArtwork: '✦ 작품 출시', previewLabel: '미리보기', curveLabel: '{type} 커브', initPriceCard: '초기 가격', supplyCard: '공급량', royaltyCard: '로열티', bondingCurveChart: '본딩 커브', priceVsSupply: '가격 vs. 공급', supply80: '80% 공급', targetPrice: '목표 가격', at80Supply: '80% 공급 시', ethToGrad: '졸업 ETH', graduationThreshold: '졸업 기준', estGasCost: '예상 가스비', deployDesc: 'Base에 배포 · {type} 커브', launchChecklist: '출시 체크리스트', stepUpload: '작품 업로드', stepTitle: '제목 & 설명', stepTicker: '티커 설정', stepCategory: '카테고리 선택', stepCurve: '커브 설정', stepAiCheck: 'AI 검토', stepWallet: '지갑 연결', stepGas: '가스 잔액 확인', stepDeploy: '배포', awaitingSubmission: '제출 대기 중…', aiCheckDescription: 'AI가 IP 충돌과 콘텐츠 기준을 검토합니다.', analyzing: '작품 분석 중…', approved: '승인됨 — 출시 준비 완료', approvedDetails: 'IP 충돌 없음 · 기준 통과', rejected: '거부됨', rejectedMessage: '잠재적 IP 충돌 감지. 검토 후 재제출하세요.', breadcrumbStudio: '스튜디오', breadcrumbNew: '새 작품', connected: '연결됨: {addr}', notConnected: '연결 안 됨' },
  vault: { portfolioValue: '포트폴리오 가치', timeframe7d: '7일', timeframe30d: '30일', timeframe90d: '90일', allocation: '배분', total: '합계', portfolioValueStat: '포트폴리오 가치', unrealizedPnl: '미실현 손익', realizedPnl: '실현 손익', ethBalance: 'ETH 잔액', myHoldings: '내 보유', txHistory: '거래 내역', asset: '자산', qty: '수량', avgBuy: '평균 매수가', current: '현재', value: '가치', pnl: '손익', chgPct: '변동%', date: '날짜', side: '방향', token: '토큰', ethSpent: '사용 ETH', buy: '매수', sell: '매도', realizedPnlClosed: '실현 손익(청산)', tradeLink: '거래 →', noResults: '결과 없음' },
  settings: { title: '설정', accountSettings: '계정 설정', accountSettingsDesc: '프로필, 보안 및 환경설정을 관리하세요.', profileSection: '프로필', usernameLabel: '사용자명', usernamePlaceholder: '사용자명', bioLabel: '소개', bioPlaceholder: '세상에 자신을 소개하세요…', saving: '저장 중…', saved: '✓ 저장됨', saveChanges: '변경 사항 저장', notificationsSection: '알림', tradeAlerts: '거래 알림', tradeAlertsDesc: '작품이 거래될 때 알림 받기', newFollowers: '새 팔로워', newFollowersDesc: '누군가 팔로우할 때', priceMilestones: '가격 마일스톤', priceMilestonesDesc: '작품이 목표 가격에 도달할 때', securitySection: '보안', authMethod: '인증 방법', authMethodDesc: 'ArtCurve에 로그인하는 방법', session: '세션', sessionDesc: '현재 로그인됨', active: '활성', dangerZone: '위험 구역', signOut: '로그아웃', signOutDesc: '이 기기에서 로그아웃' },
  wallet: { signInTitle: '지갑을 보려면 로그인하세요', signInDesc: 'GitHub, X 또는 암호화폐 지갑으로 연결하세요.', title: '지갑', yourWallet: '내 지갑', walletDesc: '신원, 잔액 및 온체인 활동을 관리하세요.', verified: '인증됨', anonymous: '익명', signOut: '로그아웃', connectedWallet: '연결된 지갑', accountAddress: '계정 주소', smartAccount: '스마트 계정 · 플랫폼 관리', copy: '복사', copied: '복사됨', explorer: '탐색기', ethBalance: 'ETH 잔액', emptyWallet: '빈 지갑', walletNotConnected: '지갑 미연결', portfolio: '포트폴리오', noPositions: '포지션 없음', holdingsCount: '{count}개 보유', holdingsCountPlural: '{count}개 보유', network: '네트워크', authMethod: '인증 방법', portfolioHoldings: '포트폴리오 보유', totalPnl: '총 손익:', linkWalletTitle: '외부 지갑 연결', linkWalletDesc: 'MetaMask 또는 다른 지갑을 연결하여 온체인 거래하세요.', noWalletsDetected: '지갑이 감지되지 않음', noWalletsHint: 'MetaMask 또는 다른 브라우저 확장 지갑을 설치하세요', getMetaMask: 'MetaMask 받기', showLess: '접기', showMore: '{count}개 더 보기', detected: '감지됨', securitySection: '보안', signInMethod: '로그인 방법', walletVerification: '지갑 인증', onChainWallet: '온체인 지갑(SIWE)', verifiedViaSiwe: 'EIP-4361 서명으로 인증됨', notVerified: '미인증', accountRole: '계정 역할', artist: '아티스트 — 작품 민팅 가능', admin: '관리자', collector: '컬렉터', userId: '사용자 ID' },
  artwork: { backToMarketplace: '마켓으로 돌아가기', marketCap: '시가총액', change24h: '24h 변동', holders: '보유자', volume24h: '24h 거래량', completion: '완성도', phase: '단계', graduated: '✦ 졸업됨', bondingCurve: '본딩 커브', priceVsSupply: '가격 vs. 공급', now: '현재', buy: '{ticker} 구매', collectorVoices: '컬렉터의 목소리', poor: '나쁨', fair: '보통', good: '좋음', great: '매우 좋음', exceptional: '탁월함', sharePerspective: '이 작품에 대한 시각을 공유하세요…', posting: '게시 중…', post: '게시', connectToShare: '시각을 공유하려면 지갑을 연결하세요.', connect: '연결', noPerspectives: '아직 시각이 없습니다.', artworkNotFound: '작품을 찾을 수 없습니다', topHolders: '상위 보유자' },
  error: { systemError: '시스템 오류', somethingWentWrong: '오류가 발생했습니다', tryAgain: '다시 시도' },
  notFound: { label: '페이지를 찾을 수 없습니다', description: '이 커브는 존재하지 않거나 아직 배포되지 않았습니다.', returnToMarket: '마켓으로 돌아가기' },
  auth: { signingIn: '로그인 중…' },
}

export default ko
