import type { Translations } from './en'

const pt: Translations = {
  nav: { marketplace: 'Mercado', trade: 'Negociar', live: 'Ao vivo', guild: 'Guilda', vault: 'Cofre', studio: 'Estúdio' },
  header: { notifications: 'Notificações', markAllRead: 'Marcar tudo como lido', allCaughtUp: 'Sem novas notificações', viewAllActivity: 'Ver toda a atividade', clearAll: 'Limpar tudo', all: 'Todos', unread: 'Não lidos', signOut: 'Sair', connectWallet: 'Conectar carteira' },
  lang: { label: 'Idioma', search: 'Pesquisar idioma…' },
  common: { viewDetailReviews: 'Ver detalhes e avaliações', buy: 'Comprar', sell: 'Vender', collect: 'Colecionar', noReviewsYet: 'Ainda sem avaliações', loading: 'Carregando…', error: 'Algo deu errado', search: 'Pesquisar…', noResults: 'Sem resultados', live: 'Ao vivo', back: 'Voltar', cancel: 'Cancelar', confirm: 'Confirmar' },
  marketplace: { title: 'Mercado ao vivo', subtitle: 'Negocie obras únicas na curva de bonding.', totalVolume: 'Volume total', listings: 'Listagens ativas', trades24h: 'Negociações 24H', all: 'Todos', search: 'Pesquisar…', race: 'Corrida', marketCap: 'Cap. de mercado', change24h: 'Variação 24h', change7d: 'Variação 7d', liveActivity: 'Atividade ao vivo' },
  trade: { markets: 'Mercados', search: 'Pesquisar…', change24h: 'Variação 24H', vol24h: 'Vol. 24H', high24h: 'Máx. 24H', low24h: 'Mín. 24H', holders: 'Detentores', progress: 'Progresso', recentTrades: 'Negociações recentes', orderBook: 'Livro de ordens', time: 'Hora', side: 'Lado', price: 'Preço', size: 'Qtd.', sizeEth: 'Qtd. (ETH)', total: 'Total', wallet: 'Carteira', priceEth: 'Preço (ETH)', bal: 'Saldo', max: 'MÁX', youPay: 'Você paga', youReceive: 'Você recebe', estimate: 'estimativa', impact: 'Impacto', minOut: 'Mín. recebido', graduationWarning: 'Esta operação graduaria a obra para DEX', youSell: 'Você vende', slippage: 'Derrapagem', confirming: 'Confirmando…', orderExecuted: 'Ordem executada', noResults: 'Sem resultados' },
  guild: { joined: 'Associado', guilds: 'Guildas', discover: 'Descobrir', myGuilds: 'Minhas guildas', statsFormat: '{count} guildas · {members} membros', createGuild: '+ Criar guilda', createModalTitle: 'Criar uma guilda', guildNameLabel: 'Nome da guilda', guildNamePlaceholder: 'ex. A Sociedade Noturna', descriptionLabel: 'Descrição', descriptionPlaceholder: 'O que sua guilda coleciona e celebra?', focusLabel: 'Foco', createButton: '✦ Criar guilda', activity: 'Atividade', chat: 'Chat', members: 'Membros', holdings: 'Participações', leave: 'Sair', joinGuild: 'Entrar na guilda', reply: 'Responder', chatPlaceholder: 'Mensagem para {name}…', collectiveHoldings: 'Participações coletivas', positions: 'Posições', noHoldingsData: 'Sem dados de participações coletivas', moreMembers: '+{count} membros', tokens: '{count} tokens', qty: 'qtd.', pctCollective: '% coletivo' },
  live: { home: 'Início', live: 'Ao vivo', artists: 'Artistas', you: 'Você', all: 'Todos', following: 'Seguindo', videos: 'Vídeos', painting: 'Pintura', drawing: 'Desenho', digital: 'Digital', sculpture: 'Escultura', mixedMedia: 'Mídia mista', trending: 'Em alta', watching: '{count} assistindo', saveToPlaylist: 'Salvar na lista', share: 'Compartilhar', report: 'Reportar', moreOptions: 'Mais opções', goLive: 'Transmitir', streamTitleLabel: 'Título da transmissão', streamTitlePlaceholder: 'O que você está criando hoje?', categoryLabel: 'Categoria', starting: 'Iniciando…', startStreaming: '● Iniciar transmissão', goLiveButton: 'Ao vivo', noContent: 'Sem conteúdo nesta categoria' },
  studio: { createArtwork: 'Criar obra', uploadPrompt: 'Soltar obra · JPG / PNG / WEBP / MP4', uploadHint: 'Máx. 50 MB · Mín. 1200×1200px', artworkTitleLabel: 'Título da obra', artworkTitlePlaceholder: 'ex. Estudo de Dissolução III', tickerLabel: 'Ticker do token', tickerHint: 'gerado automaticamente · editável', categoryLabel: 'Categoria', descriptionLabel: 'Descrição', descriptionPlaceholder: 'Descreva sua obra…', bondingCurveTypeLabel: 'Tipo de curva de bonding', totalSupplyLabel: 'Oferta total', initPriceLabel: 'Preço inicial (ETH)', creatorRoyaltyLabel: 'Royalties do criador', aiModeration: 'Moderação IA…', launchArtwork: '✦ Lançar obra', previewLabel: 'Pré-visualização', curveLabel: 'curva {type}', initPriceCard: 'Preço inicial', supplyCard: 'Oferta', royaltyCard: 'Royalties', bondingCurveChart: 'Curva de bonding', priceVsSupply: 'preço vs. oferta', supply80: '80% oferta', targetPrice: 'Preço-alvo', at80Supply: 'a 80% de oferta', ethToGrad: 'ETH para graduação', graduationThreshold: 'limiar de graduação', estGasCost: 'Gas estimado', deployDesc: 'implantar na Base · curva {type}', launchChecklist: 'Lista de verificação', stepUpload: 'Carregar obra', stepTitle: 'Título e descrição', stepTicker: 'Definir ticker', stepCategory: 'Escolher categoria', stepCurve: 'Configurar curva', stepAiCheck: 'Verificação IA', stepWallet: 'Conectar carteira', stepGas: 'Saldo de gas suficiente', stepDeploy: 'Implantar', awaitingSubmission: 'Aguardando envio…', aiCheckDescription: 'A IA verifica conflitos de PI, conteúdo proibido e padrões de qualidade.', analyzing: 'Analisando obra…', approved: 'Aprovado — Pronto para lançar', approvedDetails: 'Sem conflitos de PI · Padrões OK', rejected: 'Rejeitado', rejectedMessage: 'Possível conflito de PI detectado.', breadcrumbStudio: 'Estúdio', breadcrumbNew: 'Nova obra', connected: 'Conectado: {addr}', notConnected: 'Não conectado' },
  vault: { portfolioValue: 'Valor do portfólio', timeframe7d: '7D', timeframe30d: '30D', timeframe90d: '90D', allocation: 'Alocação', total: 'Total', portfolioValueStat: 'Valor do portfólio', unrealizedPnl: 'L&P não realizado', realizedPnl: 'L&P realizado', ethBalance: 'Saldo ETH', myHoldings: 'Minhas participações', txHistory: 'Histórico TX', asset: 'Ativo', qty: 'Qtd.', avgBuy: 'Preço médio', current: 'Atual', value: 'Valor', pnl: 'L&P', chgPct: 'Var. %', date: 'Data', side: 'Lado', token: 'Token', ethSpent: 'ETH gasto', buy: 'Comprar', sell: 'Vender', realizedPnlClosed: 'L&P realizado (fechadas)', tradeLink: 'Negociar →', noResults: 'Sem resultados' },
  settings: { title: 'Configurações', accountSettings: 'Configurações da conta', accountSettingsDesc: 'Gerencie seu perfil, segurança e preferências.', profileSection: 'Perfil', usernameLabel: 'Nome de usuário', usernamePlaceholder: 'seu_usuario', bioLabel: 'Bio', bioPlaceholder: 'Apresente-se ao mundo…', saving: 'Salvando…', saved: '✓ Salvo', saveChanges: 'Salvar alterações', notificationsSection: 'Notificações', tradeAlerts: 'Alertas de negociação', tradeAlertsDesc: 'Seja notificado quando suas obras forem negociadas', newFollowers: 'Novos seguidores', newFollowersDesc: 'Quando alguém seguir seu perfil', priceMilestones: 'Marcos de preço', priceMilestonesDesc: 'Quando uma obra atingir uma meta de preço', securitySection: 'Segurança', authMethod: 'Método de autenticação', authMethodDesc: 'Como você faz login no ArtCurve', session: 'Sessão', sessionDesc: 'Você está conectado', active: 'Ativo', dangerZone: 'Zona de perigo', signOut: 'Sair', signOutDesc: 'Sair da sua conta neste dispositivo' },
  wallet: { signInTitle: 'Entre para ver sua carteira', signInDesc: 'Conecte-se com GitHub, X ou uma carteira crypto.', title: 'Carteira', yourWallet: 'Sua carteira', walletDesc: 'Gerencie sua identidade, saldo e atividade on-chain.', verified: 'Verificado', anonymous: 'Anônimo', signOut: 'Sair', connectedWallet: 'Carteira conectada', accountAddress: 'Endereço da conta', smartAccount: 'Conta inteligente · gerenciada pela plataforma', copy: 'Copiar', copied: 'Copiado', explorer: 'Explorer', ethBalance: 'Saldo ETH', emptyWallet: 'Carteira vazia', walletNotConnected: 'Carteira não conectada', portfolio: 'Portfólio', noPositions: 'Sem posições', holdingsCount: '{count} participação', holdingsCountPlural: '{count} participações', network: 'Rede', authMethod: 'Método de auth.', portfolioHoldings: 'Participações do portfólio', totalPnl: 'L&P total:', linkWalletTitle: 'Vincular carteira externa', linkWalletDesc: 'Conecte MetaMask ou outra carteira para operar on-chain.', noWalletsDetected: 'Nenhuma carteira detectada', noWalletsHint: 'Instale MetaMask ou outra extensão de carteira', getMetaMask: 'Obter MetaMask', showLess: 'Mostrar menos', showMore: 'Ver mais {count} carteiras', detected: 'Detectado', securitySection: 'Segurança', signInMethod: 'Método de login', walletVerification: 'Verificação de carteira', onChainWallet: 'Carteira On-Chain (SIWE)', verifiedViaSiwe: 'Verificado via EIP-4361', notVerified: 'Não verificado', accountRole: 'Função da conta', artist: 'Artista — pode criar obras', admin: 'Administrador', collector: 'Colecionador', userId: 'ID do usuário' },
  artwork: { backToMarketplace: 'Voltar ao mercado', marketCap: 'Cap. de mercado', change24h: 'Variação 24h', holders: 'Detentores', volume24h: 'Volume 24h', completion: 'Conclusão', phase: 'Fase', graduated: '✦ Graduado', bondingCurve: 'Curva de bonding', priceVsSupply: 'preço vs. oferta', now: 'agora', buy: 'Comprar {ticker}', collectorVoices: 'Vozes dos colecionadores', poor: 'Ruim', fair: 'Regular', good: 'Bom', great: 'Muito bom', exceptional: 'Excepcional', sharePerspective: 'Compartilhe sua perspectiva sobre esta obra…', posting: 'Publicando…', post: 'Publicar', connectToShare: 'Conecte sua carteira para compartilhar.', connect: 'Conectar', noPerspectives: 'Ainda sem perspectivas.', artworkNotFound: 'Obra não encontrada', topHolders: 'Principais detentores' },
  error: { systemError: 'Erro do sistema', somethingWentWrong: 'Algo deu errado', tryAgain: 'Tentar novamente' },
  notFound: { label: 'Página não encontrada', description: 'Esta curva não existe — ou ainda não foi implantada.', returnToMarket: 'Voltar ao mercado' },
  auth: { signingIn: 'Entrando…' },
}

export default pt
