import type { Translations } from './en'

const zh: Translations = {
  nav: { marketplace: '市场', trade: '交易', live: '直播', guild: '公会', vault: '金库', studio: '工作室' },
  header: { notifications: '通知', markAllRead: '全部标为已读', allCaughtUp: '暂无新通知', viewAllActivity: '查看所有活动', clearAll: '清除所有', all: '全部', unread: '未读', signOut: '退出登录', connectWallet: '连接钱包' },
  lang: { label: '语言', search: '搜索语言…' },
  common: { viewDetailReviews: '查看详情和评论', buy: '购买', sell: '出售', collect: '收藏', noReviewsYet: '暂无评论', loading: '加载中…', error: '出错了', search: '搜索…', noResults: '无结果', live: '直播', back: '返回', cancel: '取消', confirm: '确认' },
  marketplace: { title: '实时市场', subtitle: '在联合曲线上交易独特艺术品。', totalVolume: '总交易量', listings: '上架中', trades24h: '24H交易', all: '全部', search: '搜索…', race: '竞赛', marketCap: '市值', change24h: '24h变动', change7d: '7d变动', liveActivity: '实时活动' },
  trade: { markets: '市场', search: '搜索…', change24h: '24H变动', vol24h: '24H成交量', high24h: '24H最高', low24h: '24H最低', holders: '持有者', progress: '进度', recentTrades: '最近交易', orderBook: '订单簿', time: '时间', side: '方向', price: '价格', size: '数量', sizeEth: '数量(ETH)', total: '总计', wallet: '钱包', priceEth: '价格(ETH)', bal: '余额', max: '最大', youPay: '你支付', youReceive: '你收到', estimate: '预估', impact: '影响', minOut: '最少收到', graduationWarning: '此交易将使艺术品毕业至DEX', youSell: '你出售', slippage: '滑点', confirming: '确认中…', orderExecuted: '订单已执行', noResults: '无结果' },
  guild: { joined: '已加入', guilds: '公会', discover: '发现', myGuilds: '我的公会', statsFormat: '{count}个公会 · {members}名成员', createGuild: '+ 创建公会', createModalTitle: '创建公会', guildNameLabel: '公会名称', guildNamePlaceholder: '例如: 夜曲协会', descriptionLabel: '描述', descriptionPlaceholder: '你的公会收藏和庆祝什么?', focusLabel: '主题', createButton: '✦ 创建公会', activity: '活动', chat: '聊天', members: '成员', holdings: '持仓', leave: '退出', joinGuild: '加入公会', reply: '回复', chatPlaceholder: '给{name}发消息…', collectiveHoldings: '集体持仓', positions: '仓位', noHoldingsData: '暂无集体持仓数据', moreMembers: '+{count}名成员', tokens: '{count}个代币', qty: '数量', pctCollective: '集体%' },
  live: { home: '首页', live: '直播', artists: '艺术家', you: '你', all: '全部', following: '关注', videos: '视频', painting: '绘画', drawing: '素描', digital: '数字', sculpture: '雕塑', mixedMedia: '混合媒介', trending: '热门', watching: '{count}人在看', saveToPlaylist: '保存到播放列表', share: '分享', report: '举报', moreOptions: '更多选项', goLive: '开始直播', streamTitleLabel: '直播标题', streamTitlePlaceholder: '今天你在创作什么?', categoryLabel: '类别', starting: '启动中…', startStreaming: '● 开始直播', goLiveButton: '直播', noContent: '此分类暂无内容' },
  studio: { createArtwork: '创建作品', uploadPrompt: '上传作品 · JPG / PNG / WEBP / MP4', uploadHint: '最大50MB · 最小1200×1200px', artworkTitleLabel: '作品标题', artworkTitlePlaceholder: '例如: 解构研究 III', tickerLabel: '代币符号', tickerHint: '自动生成 · 可编辑', categoryLabel: '类别', descriptionLabel: '描述', descriptionPlaceholder: '描述你的作品及其意义…', bondingCurveTypeLabel: '联合曲线类型', totalSupplyLabel: '总供应量', initPriceLabel: '初始价格(ETH)', creatorRoyaltyLabel: '创作者版税', aiModeration: 'AI审核中…', launchArtwork: '✦ 发布作品', previewLabel: '预览', curveLabel: '{type}曲线', initPriceCard: '初始价格', supplyCard: '供应量', royaltyCard: '版税', bondingCurveChart: '联合曲线', priceVsSupply: '价格 vs. 供应', supply80: '80%供应', targetPrice: '目标价格', at80Supply: '80%供应时', ethToGrad: '毕业ETH', graduationThreshold: '毕业门槛', estGasCost: '预估Gas费', deployDesc: '部署到Base · {type}曲线', launchChecklist: '发布清单', stepUpload: '上传作品', stepTitle: '填写标题和描述', stepTicker: '设置代币符号', stepCategory: '选择类别', stepCurve: '配置曲线', stepAiCheck: 'AI审核', stepWallet: '连接钱包', stepGas: 'Gas余额充足', stepDeploy: '部署', awaitingSubmission: '等待提交…', aiCheckDescription: 'AI检查IP冲突、禁止内容和质量标准。', analyzing: '分析作品中…', approved: '已批准 — 准备发布', approvedDetails: '无IP冲突 · 内容标准通过 · 质量OK', rejected: '已拒绝', rejectedMessage: '检测到潜在IP冲突，请检查后重新提交。', breadcrumbStudio: '工作室', breadcrumbNew: '新作品', connected: '已连接: {addr}', notConnected: '未连接' },
  vault: { portfolioValue: '投资组合价值', timeframe7d: '7天', timeframe30d: '30天', timeframe90d: '90天', allocation: '分配', total: '总计', portfolioValueStat: '投资组合价值', unrealizedPnl: '未实现盈亏', realizedPnl: '已实现盈亏', ethBalance: 'ETH余额', myHoldings: '我的持仓', txHistory: '交易历史', asset: '资产', qty: '数量', avgBuy: '平均买入', current: '当前', value: '价值', pnl: '盈亏', chgPct: '变动%', date: '日期', side: '方向', token: '代币', ethSpent: '已用ETH', buy: '买入', sell: '卖出', realizedPnlClosed: '已实现盈亏(已平仓)', tradeLink: '交易 →', noResults: '无结果' },
  settings: { title: '设置', accountSettings: '账户设置', accountSettingsDesc: '管理你的个人资料、安全和偏好设置。', profileSection: '个人资料', usernameLabel: '用户名', usernamePlaceholder: '你的用户名', bioLabel: '简介', bioPlaceholder: '向世界介绍你自己…', saving: '保存中…', saved: '✓ 已保存', saveChanges: '保存更改', notificationsSection: '通知', tradeAlerts: '交易提醒', tradeAlertsDesc: '当你的作品被交易时通知', newFollowers: '新关注者', newFollowersDesc: '当有人关注你的主页时', priceMilestones: '价格里程碑', priceMilestonesDesc: '当作品达到价格目标时', securitySection: '安全', authMethod: '认证方式', authMethodDesc: '你登录ArtCurve的方式', session: '会话', sessionDesc: '当前已登录', active: '活跃', dangerZone: '危险区域', signOut: '退出登录', signOutDesc: '在此设备上退出账户' },
  wallet: { signInTitle: '登录以查看你的钱包', signInDesc: '使用GitHub、X或加密钱包连接以访问你的投资组合。', title: '钱包', yourWallet: '我的钱包', walletDesc: '管理你的身份、余额和链上活动。', verified: '已验证', anonymous: '匿名', signOut: '退出登录', connectedWallet: '已连接钱包', accountAddress: '账户地址', smartAccount: '智能账户 · 由平台管理', copy: '复制', copied: '已复制', explorer: '浏览器', ethBalance: 'ETH余额', emptyWallet: '钱包为空', walletNotConnected: '钱包未连接', portfolio: '投资组合', noPositions: '无仓位', holdingsCount: '{count}项持仓', holdingsCountPlural: '{count}项持仓', network: '网络', authMethod: '认证方式', portfolioHoldings: '投资组合持仓', totalPnl: '总盈亏:', linkWalletTitle: '链接外部钱包', linkWalletDesc: '连接MetaMask或其他钱包以在链上交易。', noWalletsDetected: '未检测到钱包', noWalletsHint: '请安装MetaMask或其他浏览器扩展钱包', getMetaMask: '获取MetaMask', showLess: '收起', showMore: '查看更多{count}个钱包', detected: '已检测', securitySection: '安全', signInMethod: '登录方式', walletVerification: '钱包验证', onChainWallet: '链上钱包(SIWE)', verifiedViaSiwe: '已通过EIP-4361签名验证', notVerified: '未验证 — 无钱包连接', accountRole: '账户角色', artist: '艺术家 — 可以铸造作品', admin: '管理员', collector: '收藏家', userId: '用户ID' },
  artwork: { backToMarketplace: '返回市场', marketCap: '市值', change24h: '24h变动', holders: '持有者', volume24h: '24h成交量', completion: '完成度', phase: '阶段', graduated: '✦ 已毕业', bondingCurve: '联合曲线', priceVsSupply: '价格 vs. 供应', now: '现在', buy: '购买{ticker}', collectorVoices: '收藏家之声', poor: '差', fair: '一般', good: '好', great: '很好', exceptional: '卓越', sharePerspective: '分享你对这件作品的看法…', posting: '发布中…', post: '发布', connectToShare: '连接钱包以分享你的看法。', connect: '连接', noPerspectives: '暂无看法。', artworkNotFound: '未找到作品', topHolders: '最大持有者' },
  error: { systemError: '系统错误', somethingWentWrong: '出错了', tryAgain: '重试' },
  notFound: { label: '页面未找到', description: '此曲线不存在 — 或尚未部署。', returnToMarket: '返回市场' },
  auth: { signingIn: '登录中…' },
}

export default zh
